# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginGoogle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	platform :ios, '8.0'
  
  # Pods for loginGoogle
   pod 'FBSDKLoginKit'
   pod 'FBSDKShareKit'
   pod 'GoogleSignIn'

  target 'loginGoogleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end